[package]
name = "notify"
version = "5.0.0-crossbeam"
authors = [
  "Félix Saparelli <me@passcod.name>",
  "Jorge Israel Peña <jorge.israel.p@gmail.com>",
  "Michael Maurizi <michael.maurizi@gmail.com>",
  "Pierre Baillet <oct@zoy.org>",
  "Joe Wilm <joe@jwilm.com>",
  "Daniel Faust <hessijames@gmail.com>",
  "Ronny Chan <ronny@ronnychan.ca>"
]
description = "Cross-platform filesystem notification library"
documentation = "https://docs.rs/notify"
homepage = "https://github.com/passcod/notify"
repository = "https://github.com/passcod/notify.git"
readme = "README.md"
license = "CC0-1.0"
keywords = ["events", "filesystem", "notify", "watch"]
categories = ["filesystem"]
edition = "2015"

[dependencies]
bitflags = "^1.0.4"
libc = "^0.2.4"
filetime = "^0.2.1"
walkdir = "^2.0.1"
crossbeam = "^0.5.0"

[target.'cfg(target_os="linux")'.dependencies]
inotify = "^0.6.1"
mio = "^0.6.15"
mio-extras = "^2.0.5"

[target.'cfg(target_os="macos")'.dependencies]
fsevent = "^0.2.17"
fsevent-sys = "^0.1.3"

[target.'cfg(windows)'.dependencies]
winapi = "^0.3.5"
kernel32-sys = "^0.2.1"

[dev-dependencies]
tempdir = "^0.3.4"

[features]
timing_tests = []
manual_tests = []
